config/routes.rb
Rails.application.routes.draw do
  get 'operations/home'
  get 'operations/set_quantity'
  get 'operations/display_form'
  get 'operations/display_results'
  get 'operations/download_file'
  post 'operations/calculate'

  root 'operations#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/operations_controller.rb
require "#{Rails.root}/lib/code/schedule.rb"

class OperationsController < ApplicationController

  def home
  end

  def set
  end

  def display_form
  	@number_of_persons = params[:number_of_persons].to_i
    if @number_of_persons == 0
    	flash.now[:error] = 'Please enter a number'
      	render "set_quantity"
    else
    	render "display_form"
    end
  end

  def calculate
  	if valid_inputs_for_calculate? params
    	list_of_persons = params[:persons]
    	persons_per_group = params[:maximum_persons_per_group].to_i
    	number_of_rounds = params[:number_of_rounds].to_i
      times_to_run = params[:times_to_run].to_i

    	dsw = ScheduleDatasetWrapper.new(:seminarians_per_group => persons_per_group, :number_of_rounds => number_of_rounds, :seminarian_list => list_of_persons, :times_to_run => times_to_run)
    	@schedule_dataset = dsw.best_dataset
    	@groups = @schedule_dataset.groups.sort_by{|g| [g.position, g.day]}

      #write_new_file @schedule_dataset

    	render "display_results"

    else
      @number_of_persons = params[:persons].count
      render "display_form"
    end
  end

  def download_file
    send_file(Rails.root + "tmp/schedule.txt")
  end

  private

    def valid_inputs_for_calculate? params
      if params[:maximum_persons_per_group].to_i == 0 || params[:number_of_rounds].to_i == 0 || params[:times_to_run].to_i == 0
        flash.now[:error] = 'Please enter numbers for "Persons per group," "Number of rounds," and "Times to run."'
        return false
      elsif any_persons_blank? params[:persons]
        flash.now[:error] = 'Please enter a name for each person.'
        return false
      elsif any_persons_identical? params[:persons]
        flash.now[:error] = 'Please enter a different name for each person.'
        return false
      else
        return true
      end
    end

    def any_persons_blank? persons
      persons.each do |p|
        return true if p.blank?
      end
      return false
    end

    def any_persons_identical? persons
      persons.uniq.count < persons.count
    end

    def write_new_file dataset
      File.open(Rails.root + "tmp/schedule.txt", "w") do |f|     
        f.write(dataset.print_to_string)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mixer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |name, msg| %>
  	  <%= content_tag :div, msg, :class => name %>
  	<% end %>

    <%= yield %>
  </body>
</html>

app/views/operations/display_form.html.erb
<div class="wrapper">
	<%= form_tag operations_calculate_path, :method => 'post' do %>
		<p><%= label_tag :maximum_persons_per_group %>: <%= text_field_tag :maximum_persons_per_group %></p>
		<p><%= label_tag :number_of_rounds %>: <%= text_field_tag :number_of_rounds %></p>
		<p><%= label_tag :times_to_run %>: <%= text_field_tag :times_to_run %></p>
		<p>(Try setting "Times to run" at about 700. If you receive an error try a lower number.)</p>

		<% (1..@number_of_persons).each do |n| %>
			<p><%= label_tag "Person #{n}" %>: <%= text_field_tag 'persons[]' %></p>
		<% end %>
      	<p><%= submit_tag "Submit" %></p>
	<% end %>
</div>

app/views/operations/display_results.html.erb
<h3 class="center">The mix has the following statistics:</h3>
<p class="center">
	Number of times a pair of persons were never in the same group: <%= @schedule_dataset.number_of_zeros %><br />
	Number of times a pair of persons were in the same group once: <%= @schedule_dataset.number_of_singles %><br />
	Number of times a pair of persons were in the same group twice: <%= @schedule_dataset.number_of_doubles %><br />
	Number of times a pair of persons were in the same group three times: <%= @schedule_dataset.number_of_triples %><br />
	Number of times a pair of persons were in the same group four times or more: <%= @schedule_dataset.number_of_quad_plus %><br /><br/>
	<% #link_to "Click here to download text file of results", operations_download_file_path %>
</p>

<% (1..@schedule_dataset.number_of_rounds).each do |n| %>
	<table border="1">
		<caption>Round <%= n %></caption>
		<tr>
			<% (1..@schedule_dataset.number_of_groups).each do |i| %>
				<th>Section <%= i %></th>
			<% end %>
		</tr>
		
		<% (1..@schedule_dataset.seminarians_per_group).each do |i| %>
			<tr>
			<% @groups.select{|g| g.position == n}.sort_by{|g| g.day}.each do |group| %>
				<td><%= group.seminarians[i-1].try(:name) %></td>
			<% end %>
			</tr>
		<% end %>
	</table>
<% end %>

app/views/operations/home.html.erb
<h1 class="center">Welcome to People Mixer</h1>
<div class="text">
	<p class="center">This is an application that takes a group of people and mixes them together into small groups, trying
	to create as many unique groups as possible.  There are three basic goals: 1) try to pair all persons once or twice, 
	but no more than twice; 2) try to assign each person to every section throughout many rounds; and 3) try to make every
	group approximately the same size.</p>
	<p class="center">The application tries to find an optimal mixture x times and then chooses the best out of these
	x options.  Depending on the size of the initial group, this means that the program can take some time to run.  
	Please be patient.</p>
</div>
<div class="wrapper"><%= link_to "Begin", operations_set_quantity_path, :class => 'button' %></div>

app/views/operations/set_quantity.html.erb
<p class="center">Please enter the total number of persons you wish to mix into groups.</p>
<div class="wrapper">
	<%= form_tag operations_display_form_path, :method => 'get' do %>
		<p><%= label_tag :number_of_persons %>: <%= text_field_tag :number_of_persons %></p>
      	<p><%= submit_tag "Next" %></p>
	<% end %>
</div>